baseurl: /
languageCode: en-us
title: Imran Kocabiyik - Personal Website
theme: hugo-lithium
# googleAnalytics: ''
# disqusShortname: ''
publishDir: "../kocabiyik.github.io"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  tr: blog/:section/:slug/
  en: blog/:section/:slug/
menu:
  social:
    - name: GitHub
      url: https://github.com/kocabiyik/
      icon: x
    - name: Twitter
      url: https://twitter.com/imrankocabiyik
      icon: x
    - name: LinkedIn
      url: https://www.linkedin.com/in/imrankocabiyik/
      icon: x
    - name: StackOverflow
      url: https://stackoverflow.com/users/5070121/imran-kocabiyik
      icon: x
  main:
    - name: About
      url: /about/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
categories:
  - data
  - deep-learning
